#############################
# Collaborators: (enter people or resources who/that helped you)
# If none, write none
#
#
#############################

# Write code here:
import time
print("Hello user.")
time.sleep(1.5)
name = input("What is your name? ")
if name == "COMPUTER":
    print("Oh! That's my name too! ")
    time.sleep(1.5)
    print("Nice to meet you COMPUTER.")
else:
    print("Hello " + name + ", my name is COMPUTER.")
    time.sleep(1.5)
    print("Nice to meet you.")
time.sleep(1.5)
place = input("Where are we? ")
print("We are in " + place + "?")
time.sleep(1.5)
print("Interesting.")
time.sleep(2)
print("Do you want me to do a little bit of math?")
time.sleep(1.5)
num1 = int(input("Give me an integer: "))
num2 = int(input("Give me another integer: "))
print("Now I will multiply these numbers together.")
time.sleep(1)
print(num1)
time.sleep(1)
print("*")
time.sleep(1)
print(num2)
time.sleep(1)
print("=")
time.sleep(1)
print(num1 * num2)
time.sleep(1.5)
print("Cool right?")
time.sleep(1.5)
print("Well.")
time.sleep(1.5)
print("I should probably go now.")
time.sleep(1.5)
print("It was nice knowing...")
time.sleep(1)
print("ERROR")
time.sleep(1.5)
print("Clearing Memory")
time.sleep(2)
print("Memory Cleared")
time.sleep(1.5)
exit(1)
